server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/aclogin
    username: root
    password: 2021_Accenture
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1
    host: 127.0.0.1
    port: 6379
    database: 1
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:/mybatis-config.xml




